### ISSUE TITLE
[Go] Versions v3.x.y do not work

### ISSUE THREAD

**Issue by manhtukhang** [sonatype-nexus-community/nexus-repo-api-client#11]
Please see the original issue here:
https://github.com/sonatype-nexus-community/nexus-repo-api-client-go/issues/1

**Comment by madpah** [comment]
As per response on https://github.com/sonatype-nexus-community/nexus-repo-api-client-go/issues/1:

> Thanks for reporting this @manhtukhang.
>
> Releases prior to v3.x.x were tests/pre-releases and should not be used. This is a community project and thus has no guaranteed support.
>
> In future if we have to bump the major version, I agree we should follow your great recommendation.
> 
> We are aware of multiple instances where v3.x.x of this library is being used successfully.
